version: "3.8"
services:
  frontend:
    build: ./frontend
    working_dir: /app
    ports:
      - 80:3001
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    working_dir: /app
    environment:
      - PORT=3000
      - DB1_URI=postgres://api:123987@db1:5432/db
      - DB2_URI=mongodb://api:123987@db2:27017/
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db1
      - db2
  db1:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=123987
      - POSTGRES_DB=db
    volumes:
      - db_1:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=123987
      - MONGO_INITDB_DATABASE=db
    volumes:
      - db_2:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js
volumes:
  db_1:
  db_2:
